name: Build

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build-mac:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npx electron-builder --mac
      - uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: dist/*.dmg

  build-win:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npx electron-builder --win
      - uses: actions/upload-artifact@v4
        with:
          name: win-build
          path: dist/*.exe
